version: '3'

services:
  mongo:
    image: mongo:3.4
    container_name: mongodb
    restart: always
    ports:
      - "${mongo_port}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_pwd}
