version: '3'

services:
  db:
    image: postgres:10.6-alpine
    restart: always
    ports:
      - ${pg_port}:5432
    environment:
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_pwd}
      POSTGRES_DB : ${pg_db}
